{
	"version": 1527085396,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/madeira-sheet0.png",
		"images/logo-sheet0.png",
		"images/nomejgo.png",
		"images/ibaralho-sheet0.png",
		"images/carta-sheet0.png",
		"images/carta-sheet1.png",
		"images/sensorcartas-sheet0.png",
		"images/botãohome-sheet0.png",
		"images/botãosom-sheet0.png",
		"images/botãosom-sheet1.png",
		"images/botãomusica-sheet0.png",
		"images/botãomusica-sheet1.png",
		"images/sprite-sheet0.png",
		"images/imoeda-sheet0.png",
		"media/iwan gabovitch - dark ambience loop.ogg",
		"media/draw.m4a",
		"media/draw.ogg",
		"media/passturn.m4a",
		"media/passturn.ogg",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/untap.m4a",
		"media/untap.ogg",
		"media/path to lake land.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}